import re

with open('frontend/src/pages/Workspace.jsx', 'r') as f:
    content = f.read()

upload_ui = """
                      {project?.user_documents && project.user_documents.length > 0 && (
                        <div className="w-full mt-6 text-left border-t border-nude-700/50 pt-4">
                          <h4 className="text-sm font-medium text-nude-300 mb-3">Ingested Documents & Summaries:</h4>
                          <div className="flex flex-col gap-3">
                            {project.user_documents.map((doc, idx) => (
                              <details key={doc.id || idx} className="group bg-nude-900 border border-nude-800 rounded-md overflow-hidden">
                                <summary className="p-3 flex justify-between items-center cursor-pointer hover:bg-nude-850/50 select-none">
                                  <div className="flex items-center gap-2">
                                    <span className="group-open:rotate-90 transition-transform text-nude-600 mr-1">▶</span>
                                    <BookOpen size={14} className="text-accent" />
                                    <span className="text-xs font-mono text-nude-200">{doc.filename}</span>
                                  </div>
                                  <span className="text-[10px] text-nude-500 font-mono bg-nude-800 px-2 py-0.5 rounded">
                                    {doc.chunk_count} Chunks
                                  </span>
                                </summary>
                                <div className="p-4 border-t border-nude-800 text-xs text-nude-400 font-sans whitespace-pre-wrap leading-relaxed bg-nude-900/50">
                                  <div className="text-[10px] text-accent uppercase tracking-widest font-mono mb-2">Master Summary Generated by AI:</div>
                                  {doc.master_summary || "No summary available."}
                                </div>
                              </details>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
"""

pattern = re.compile(r'\{project\?\.user_documents.*?</div>\s*\}\)\}\s*</div>\s*</div>\s*\)\}\s*</div>', re.DOTALL)

new_content = pattern.sub(upload_ui.strip(), content)

with open('frontend/src/pages/Workspace.jsx', 'w') as f:
    f.write(new_content)

print("Updated Workspace.jsx")
