"""
Design Review Agent.

Reviews the architecture spec generated by the MasterPlanner BEFORE
it is approved by the user. It looks for architectural flaws, missing
components, and bottleneck risks.
"""

from __future__ import annotations
import logging
import json
import re
from typing import Optional, Dict, Any, Tuple

from core.llm_client import LLMClient
from models.hierarchy import ArchitectureSpec

log = logging.getLogger(__name__)


class DesignReviewer:
    """Critiques system architecture before execution begins."""

    SYSTEM_PROMPT = """You are an elite Staff Software Engineer reviewing an architectural design.
Your job is to identify fatal flaws, missing components, or serious risks in the proposed system.

Check for:
1. Missing obvious components (e.g., a web app without a router or database connection).
2. God classes / monoliths (a service doing way too many things).
3. Circular dependencies.
4. Security risks (e.g., raw SQL execution, no auth).

You must output a STRICT JSON object:
{
  "is_approved": true | false,
  "critique": "Overall assessment of the architecture.",
  "flaws": [
    "Specific fatal flaw 1",
    "Specific fatal flaw 2"
  ],
  "suggestions": [
    "Specific suggestion to fix flaw 1"
  ]
}

If the architecture is generally sound and production-ready, set is_approved to true.
Only set to false if there are FATAL flaws that will cause the system to fail.
Output ONLY the JSON object. No markdown. No explanation."""

    def __init__(self, llm: LLMClient):
        self.llm = llm

    async def review_architecture(self, arch: ArchitectureSpec) -> Tuple[bool, str]:
        """
        Review the architecture spec.
        
        Returns:
            (is_approved, review_report)
        """
        log.info("DesignReviewer: analyzing architecture %s", arch.name)
        
        # Format the architecture for review
        arch_dict = arch.to_dict()
        arch_text = json.dumps(arch_dict, indent=2)
        
        prompt = f"=== ARCHITECTURE DESIGN ===\n{arch_text}\n\nReview this architecture now."

        raw_output = await self.llm.generate(prompt=prompt, system=self.SYSTEM_PROMPT)
        
        return self._parse_result(raw_output)

    def _parse_result(self, raw_output: str) -> Tuple[bool, str]:
        """Parse LLM output into (is_approved, report)."""
        # Strip think blocks
        cleaned = re.sub(r'<think>.*?</think>', '', raw_output, flags=re.DOTALL)
        
        # Extract JSON
        json_match = re.search(r'```(?:json)?\s*\n?(.*?)\n?```', cleaned, re.DOTALL)
        if json_match:
            cleaned = json_match.group(1)

        cleaned = cleaned.strip()
        start = cleaned.find('{')
        end = cleaned.rfind('}')
        if start >= 0 and end > start:
            cleaned = cleaned[start:end + 1]

        try:
            data = json.loads(cleaned)
            is_approved = data.get("is_approved", True)
            
            report_lines = []
            if data.get("critique"):
                report_lines.append(f"Assessment: {data['critique']}")
            
            if data.get("flaws"):
                report_lines.append("\nIdentified Flaws:")
                for flaw in data["flaws"]:
                    report_lines.append(f"  - {flaw}")
                    
            if data.get("suggestions"):
                report_lines.append("\nSuggestions:")
                for sug in data["suggestions"]:
                    report_lines.append(f"  - {sug}")
                    
            return is_approved, "\n".join(report_lines)
            
        except json.JSONDecodeError as e:
            log.warning("DesignReviewer failed to parse JSON: %s", e)
            return True, "Auto-approved (JSON parse error during review)."
